# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FactuurMaker', '0001_initial'),
        ('AgreementModule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FactuurMaker.Company'),
            preserve_default=False,
        ),
    ]
