language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - sh travis/setup.sh
script: coverage run --source=agreements,companies,hour_registration,invoices,mail,orders,settings,statistics,utils manage.py test
