language: python
python:
  - "3.5"
install:
  - pip install -r requirements.txt
  - sh travis/setup.sh
script: coverage run --source=Agreements,Blog,Companies,HourRegistration,Invoices,Mail,Orders,Settings,Statistics,Utils python3 manage.py test
