language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - sh travis/setup.sh
script: coverage run --source=Agreements,Blog,Companies,HourRegistration,Invoices,Mail,Orders,Settings,Statistics,Utils manage.py test
