version: '2'

services:
  web:
    build: '.'
    image: 'websource'
    ports:
      - '8000:8000'
    env_file: '.env'
    depends_on:
      - redis
      - postgres
    volumes:
      - ./:/invoicegen
    entrypoint:
      - /invoicegen/docker-entrypoint.sh

  daphne_worker:
    image: 'websource'
    env_file: '.env'
    command: 'python3 manage.py runworker'
    volumes_from:
      - web
    depends_on:
      - web

  celery_worker:
    image: 'websource'
    env_file: '.env'
    command: 'su -m workeruser -c "celery -A InvoiceGen worker -l info"'
    volumes_from:
      - web
    depends_on:
      - web

  postgres:
    container_name: 'postgres'
    image: 'postgres:9.5.7'
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data/'

  redis:
    container_name: 'redis'
    image: 'redis:3.2.0'
    ports:
      - '127.0.0.1:6379:6379'

volumes:
  pgdata: