version: "2"

services:
  redis:
    image: redis:latest
  web:
    build: .
    command: /usr/bin/supervisord
    volumes:
      - .:/invoicegen
    ports:
      - "8000:8000"
    links:
      - redis
