# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_created', models.DateField()),
                ('contents', models.TextField()),
                ('invoice_number', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('paid', models.BooleanField(default=False)),
                ('to_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.Company')),
            ],
        ),
    ]
