# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import invoices.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_created', models.DateField()),
                ('invoice_number', models.CharField(max_length=100)),
                ('paid', models.BooleanField(default=False)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=100)),
                ('btw_amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('invoice_file', models.FileField(null=True, upload_to='invoice-pdfs/%Y/%m/%d', validators=[invoices.models.IncomingInvoice.validate_file_extension])),
                ('received_date', models.DateField()),
            ],
            options={
                'permissions': (('view_invoice', 'Kan factuur bekijken'),),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutgoingInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_created', models.DateField()),
                ('invoice_number', models.CharField(max_length=100)),
                ('paid', models.BooleanField(default=False)),
                ('expiration_date', models.DateField()),
                ('url', models.CharField(max_length=32, null=True)),
                ('to_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
            ],
            options={
                'permissions': (('view_invoice', 'Kan factuur bekijken'),),
                'abstract': False,
            },
        ),
    ]
