# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 15:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2016, 6, 14, 15, 14, 58, 183958)),
            preserve_default=False,
        ),
    ]
