# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 11:07
from __future__ import unicode_literals

import Invoices.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_remove_product_invoice'),
        ('Companies', '0001_initial'),
        ('Invoices', '0002_invoice_expiration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_created', models.DateField()),
                ('invoice_number', models.IntegerField()),
                ('paid', models.BooleanField(default=False)),
                ('subtotal', models.IntegerField()),
                ('btw_amount', models.IntegerField()),
                ('invoice_file', models.FileField(null=True, upload_to=Invoices.models.IncomingInvoice.generate_filename, validators=[Invoices.models.IncomingInvoice.validate_file_extension])),
                ('received_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutgoingInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_created', models.DateField()),
                ('invoice_number', models.IntegerField()),
                ('paid', models.BooleanField(default=False)),
                ('total_amount', models.IntegerField()),
                ('expiration_date', models.DateField()),
                ('to_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Companies.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='to_company',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
