# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 10:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Invoices', '0003_auto_20160624_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='incominginvoice',
            name='received_date',
            field=models.DateField(default=datetime.datetime(2016, 6, 24, 10, 5, 3, 95085, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
