# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 11:19
from __future__ import unicode_literals

import Invoices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoices', '0003_auto_20160624_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incominginvoice',
            name='invoice_file',
            field=models.FileField(null=True, upload_to='invoice-pdfs/%Y/%m/%d', validators=[Invoices.models.IncomingInvoice.validate_file_extension]),
        ),
    ]
