# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoices', '0006_remove_outgoinginvoice_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoinginvoice',
            name='url',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
