# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_auto_20170717_1936'),
        ('invoices', '0002_invoicetemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('paid', 'Betaald'), ('cancelled', 'Geannuleerd'), ('pending', 'Gemaakt')], max_length=20)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=99)),
            ],
        ),
        migrations.CreateModel(
            name='BunqRequest',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payment.Payment')),
                ('counterparty_email', models.EmailField(max_length=254, null=True)),
                ('counterparty_iban', models.CharField(max_length=34, null=True)),
                ('counterparty_phone', models.CharField(max_length=34, null=True)),
                ('bunq_request_id', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('to_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
            ],
            bases=('payment.payment',),
        ),
        migrations.CreateModel(
            name='MolliePayment',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payment.Payment')),
                ('payment_id', models.IntegerField()),
            ],
            bases=('payment.payment',),
        ),
        migrations.AddField(
            model_name='payment',
            name='for_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.OutgoingInvoice'),
        ),
    ]
