# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 09:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import tenant_schemas.postgresql_backend.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_url', models.CharField(max_length=128, unique=True)),
                ('schema_name', models.CharField(max_length=63, unique=True, validators=[tenant_schemas.postgresql_backend.base._check_schema_name])),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('subdomain', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('customer_number', models.IntegerField()),
                ('valid_until', models.DateTimeField(default=datetime.datetime(2017, 3, 4, 10, 13, 37, 9343))),
                ('on_trial', models.BooleanField(default=True)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
