# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 09:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenants', '0002_auto_20170201_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 4, 10, 40, 53, 633261)),
        ),
    ]
