DEFAULT_PDF = 'pdf_default_template'
DEFAULT_DOCX = 'docx_default_template'
COLOR_UP = 'color_up'
COLOR_DOWN = 'color_down'
SITE_NAME = 'site_name'
BUNQ_API_KEY = 'bunq_api_key'
DEFAULT_BUNQ_ACCOUNT = 'default_bunq'
