CLIENT_NAME_CONSTANT = '<NAAM_OPDRACHTGEVER>'
CLIENT_CITY_ZIPCODE_CONSTANT = '<POSTCODE_PLAATS_OPDRACHTGEVER>'
CLIENT_ADDRESS_CONSTANT = '<ADRES_OPDRACHTGEVER>'
CLIENT_COMPANY_NAME_CONSTANT = '<NAAM_OPDRACHTGEVER>'
CONTRACTOR_NAME_CONSTANT = '<MIJN_NAAM>'
CONTRACTOR_CITY_ZIPCODE_CONSTANT = '<MIJN_POSTCODE_EN_WOONPLAATS>'
CONTRACTOR_ADDRESS_CONSTANT = '<MIJN_ADRES>'
OPDRACHT_OMSCHRIJVING_CONSTANT = '<OMSCHRIJVING_OPDRACHT>'
KVK_CONSTANT = '<KVK_NUMMER>'
BTW_NUMMER = '<BTW_NUMMER>'
IBAN = '<IBAN>'
DEFAULT_VARIABLE_LIST = [CLIENT_NAME_CONSTANT,
                         CLIENT_CITY_ZIPCODE_CONSTANT,
                         CLIENT_ADDRESS_CONSTANT,
                         CLIENT_COMPANY_NAME_CONSTANT,
                         CONTRACTOR_NAME_CONSTANT,
                         CONTRACTOR_CITY_ZIPCODE_CONSTANT,
                         CONTRACTOR_ADDRESS_CONSTANT,
                         OPDRACHT_OMSCHRIJVING_CONSTANT,
                         KVK_CONSTANT,
                         BTW_NUMMER,
                         IBAN]
AGREED_TEXT_CONSTANT = 'Ik ga akkoord'
