# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city_and_zipcode', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('iban', models.CharField(max_length=200)),
                ('kvk', models.CharField(max_length=10, null=True)),
                ('btw_number', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
