# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='btw_number',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='kvk',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
