# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Settings', '0002_auto_20160624_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='last_updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
