# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Settings', '0003_setting_last_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
