# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedrijfsnaam', models.CharField(max_length=200)),
                ('bedrijfsadres', models.CharField(max_length=200)),
                ('bedrijfsplaats_en_postcode', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_created', models.DateField()),
                ('contents', models.TextField()),
                ('invoice_number', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('paid', models.BooleanField(default=False)),
                ('to_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FactuurMaker.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_received', models.DateField()),
                ('date_deadline', models.DateField()),
                ('quantity', models.IntegerField()),
                ('identification_number', models.IntegerField(null=True)),
                ('briefing', models.TextField(blank=True)),
                ('done', models.BooleanField(default=False)),
                ('price_per_quantity', models.FloatField(default=0.25)),
                ('from_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FactuurMaker.Company')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FactuurMaker.Invoice')),
            ],
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=200)),
                ('adres', models.CharField(max_length=200)),
                ('plaats_en_postcode', models.CharField(max_length=200)),
                ('emailadres', models.CharField(max_length=200)),
                ('iban', models.CharField(max_length=200)),
            ],
        ),
    ]
