# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FactuurMaker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax_rate',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price_per_quantity',
            field=models.FloatField(),
        ),
    ]
