# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FactuurMaker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='site_name',
            field=models.CharField(default='InvoiceGen', max_length=50),
        ),
    ]
