# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FactuurMaker', '0018_auto_20151107_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='paid',
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='from_address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='to_address',
            field=models.TextField(default=''),
        ),
    ]
