# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FactuurMaker', '0019_auto_20151220_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companysetting',
            old_name='bedrijfsplaats',
            new_name='bedrijfsplaats_en_postcode',
        ),
        migrations.RenameField(
            model_name='usersetting',
            old_name='woonplaats',
            new_name='plaats_en_postcode',
        ),
    ]
