# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_default_price_per_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
