# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Companies', '0002_company_company_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'permissions': (('view_company', 'Kan opdrachtgever bekijken'),)},
        ),
    ]
