# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Companies', '0003_auto_20161125_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_default_price_per_quantity',
            field=models.FloatField(null=True),
        ),
    ]
