# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_by_client', models.BooleanField(default=False)),
                ('signed_by_client_at', models.DateTimeField(null=True)),
                ('signature_file_client', models.ImageField(null=True, upload_to='signatures')),
                ('signature_file_contractor', models.ImageField(null=True, upload_to='signatures')),
                ('signed_by_contractor', models.BooleanField(default=False)),
                ('signed_by_contractor_at', models.DateTimeField(null=True)),
                ('client_name', models.CharField(max_length=200)),
                ('client_emailaddress', models.CharField(max_length=200)),
                ('agreement_text_copy', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('url', models.CharField(max_length=50)),
            ],
            options={
                'permissions': (('view_agreement', 'Kan overeenkomst bekijken'),),
            },
        ),
        migrations.CreateModel(
            name='AgreementText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('text', models.TextField()),
                ('edited_at', models.DateTimeField()),
            ],
            options={
                'permissions': (('view_agreementtext', 'Kan modelovereenkomst aanmaken'),),
            },
        ),
        migrations.AddField(
            model_name='agreement',
            name='agree_text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agreements.AgreementText'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='article_concerned',
            field=models.ManyToManyField(to='orders.Product'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company'),
        ),
    ]
