# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementTextVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgreementVariableInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True)),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agreements.AgreementTextVariable')),
            ],
        ),
        migrations.RenameField(
            model_name='agreement',
            old_name='agree_text',
            new_name='agreement_text',
        ),
        migrations.AddField(
            model_name='agreement',
            name='agremeent_text_variables',
            field=models.ManyToManyField(to='agreements.AgreementVariableInstance'),
        ),
        migrations.AddField(
            model_name='agreementtext',
            name='variables',
            field=models.ManyToManyField(to='agreements.AgreementTextVariable'),
        ),
    ]
