# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agreements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='signature_file',
            field=models.ImageField(null=True, upload_to='signatures'),
        ),
    ]
