# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agreements', '0002_agreement_signature_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agreement',
            old_name='signature_file',
            new_name='signature_file_client',
        ),
        migrations.AddField(
            model_name='agreement',
            name='signature_file_contractor',
            field=models.ImageField(null=True, upload_to='signatures'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='signed_by_contractor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agreement',
            name='signed_by_contractor_at',
            field=models.DateTimeField(null=True),
        ),
    ]
