# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 08:01
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0002_auto_20170811_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreementtext',
            name='text',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
