# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agreements', '0003_auto_20160610_1651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agreement',
            options={'permissions': (('view_agreement', 'Kan overeenkomst bekijken'),)},
        ),
        migrations.AlterModelOptions(
            name='agreementtext',
            options={'permissions': (('view_agreementtext', 'Kan modelovereenkomst aanmaken'),)},
        ),
    ]
