# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Orders', '0003_product_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.Product')),
            ],
        ),
    ]
