# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HourRegistration', '0002_hourregistration_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hourregistration',
            options={'permissions': (('view_hourregistration', 'Kan urenregistraties bekijken'),)},
        ),
    ]
