# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('to', models.EmailField(max_length=254)),
                ('cc', models.EmailField(max_length=254, null=True)),
                ('bcc', models.EmailField(max_length=254, null=True)),
                ('contents', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(null=True)),
                ('document_attached', models.BooleanField(default=False)),
            ],
            options={
                'permissions': (('view_email', 'Kan verzonden e-mailberichten bekijken'),),
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('contents', models.TextField()),
            ],
        ),
    ]
