# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='sent_at',
            field=models.DateTimeField(null=True),
        ),
    ]
