# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mail', '0002_email_sent_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'permissions': (('view_email', 'Kan verzonden e-mailberichten bekijken'),)},
        ),
    ]
