# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_received', models.DateField()),
                ('date_deadline', models.DateField()),
                ('quantity', models.IntegerField()),
                ('identification_number', models.CharField(max_length=100, null=True)),
                ('briefing', models.TextField(null=True)),
                ('done', models.BooleanField(default=False)),
                ('price_per_quantity', models.FloatField()),
                ('tax_rate', models.IntegerField(null=True)),
                ('from_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.OutgoingInvoice')),
            ],
            options={
                'permissions': (('view_product', 'Kan opdrachten inzien'),),
            },
        ),
    ]
