# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0001_initial'),
        ('Invoices', '0003_auto_20160624_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Invoices.OutgoingInvoice'),
        ),
    ]
