# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Invoices', '0003_auto_20160624_1107'),
        ('Orders', '0002_remove_product_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Invoices.OutgoingInvoice'),
        ),
    ]
