# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0004_auto_20161018_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tax_rate',
            field=models.IntegerField(null=True),
        ),
    ]
