# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0005_auto_20161121_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': (('view_product', 'Kan opdrachten inzien'),)},
        ),
    ]
